#!/bin/bash
# Author: Enrico Corsaro - May 2014
# e-mail: emncorsaro@gmail.com
# usage ./multirun <KIC_ID> <starting_process_number> <Nprocesses> <output SubDir>
# Generates folders and starts a separate computation for each folder, saving the results inside

make -j 4
echo "Start processes from #$2, for a total of $3 processes"
echo "Get results from $4 sub-directory"
dir="/YOUR_LOCAL_PATH_HERE/PeakBagging/results/"
echo "General directory: $dir"

for ((i=$2; i<($2+$3); i++))
do
    if [ $i -le 9 ]; then
        mkdir "$dir"KIC$1/$4/0$i
        ./peakbagging $1 $4 0$i &
    else
        mkdir "$dir"KIC$1/$4/$i
        ./peakbagging $1 $4 $i &
    fi
done

# ./merger $1 $2 $3 $4
